#!/usr/bin/env bash

if [[ $# -ge 1 ]]; then
    args="${*:2}"
    selected=$(find "$1" $args -type d | fzf)
else
    selected=$(find ~/ ~/projects ~/work ~/personal -mindepth 1 -maxdepth 4 -type d -not -path "$HOME/Library*" | fzf --exact)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
