#!/bin/bash

if [[ -q $1 ]]; then 
    case $1 in
        "--help" | "-h")
            echo "plan [options]"
            echo ""
            echo ""
            ;;
        "today")
            ;;
        "tomorrow")
            ;;
        *)
            echo "unknown option"
            exit 1
            ;;
    esac
else; then

fi
